// ============================================================
// text.js - 全UI文言の一元管理
// ============================================================
'use strict';

const T = {
  // タイトル
  gameTitle: '六輝のオーブ',
  gameSubtitle: '- Six Lights of Eldia -',
  titleNewGame: 'はじめから',
  titleContinue: 'つづきから',
  titleSettings: 'せってい',
  noSaveData: 'セーブデータがありません。「はじめから」を選んでください。',
  brokenSaveData: 'セーブデータが壊れていたため、新しく始めます。',

  // キャラクターメイク
  charMakeTitle: '主人公をつくる',
  charMakeName: '名前を入力してください',
  charMakeClass: 'クラスを選んでください',
  charMakeConfirm: 'この内容ではじめますか？',
  nameEmpty: '名前を入力してください（1文字以上）',
  kanaDone: '決定',
  kanaBack: 'けす',
  kanaPage: 'カナ',

  // メニュー
  menuStatus: 'つよさ',
  menuSkill: 'スキル',
  menuItem: 'どうぐ',
  menuEquip: 'そうび',
  menuFormation: 'ならびかえ',
  menuSettings: 'せってい',
  menuSave: 'セーブ',
  menuClose: 'とじる',
  gold: 'G',

  // せってい
  settingBgm: 'BGM',
  settingSe: '効果音',
  settingVolume: '音量',
  settingOn: 'ON',
  settingOff: 'OFF',
  settingReduceFx: '演出ひかえめ',
  settingSaved: '設定を保存しました。',

  // セーブ・ロード
  savePrompt: 'セーブしますか？',
  saveDone: 'セーブしました。',
  saveFailed: 'セーブに失敗しました。ブラウザの保存領域を確認してください。',
  loadDone: '冒険を再開します。',

  // ステータス
  statLv: 'Lv', statHp: 'HP', statMp: 'MP',
  statAtk: 'ちから', statDef: 'まもり', statAgi: 'すばやさ', statMag: 'かしこさ', statLuk: 'うんのよさ',
  statExp: '経験値', statNext: '次のLvまで',
  slotWeapon: '武器', slotArmor: 'よろい', slotShield: '盾', slotAcc: '装飾品',
  equipNone: '（なし）',
  equipCannot: 'このクラスは装備できません。',
  statusPoison: 'どく', statusSleep: 'ねむり', statusParalysis: 'マヒ', statusDead: '戦闘不能',

  // どうぐ
  itemUseWho: 'だれに使いますか？',
  itemNoItems: 'どうぐを持っていない。お店で買うか、宝箱を探そう。',
  itemCannotUse: 'ここでは使えない。',
  itemNoEffect: 'しかし何も起こらなかった。',
  inventoryFull: 'これ以上持てない。',

  // 戦闘
  battleStart: (name) => `${name}が あらわれた！`,
  battleStartGroup: 'まものの群れが あらわれた！',
  cmdFight: 'たたかう',
  cmdSkill: 'スキル',
  cmdGuard: 'ぼうぎょ',
  cmdItem: 'どうぐ',
  cmdFlee: 'にげる',
  whoseTurn: (name) => `${name}のターン`,
  attack: (name) => `${name}の こうげき！`,
  critical: '会心の一撃！！',
  damage: (name, dmg) => `${name}に ${dmg}のダメージ！`,
  noDamage: (name) => `${name}には 効かなかった！`,
  weak: '弱点をついた！',
  resist: '効きがわるい…',
  absorb: (name) => `${name}は 攻撃を吸収した！`,
  heal: (name, v) => `${name}のHPが ${v}回復した！`,
  healMp: (name, v) => `${name}のMPが ${v}回復した！`,
  useSkill: (name, skill) => `${name}は ${skill}をつかった！`,
  useItem: (name, item) => `${name}は ${item}をつかった！`,
  guard: (name) => `${name}は 身を守っている。`,
  notEnoughMp: 'MPが足りない！',
  fleeSuccess: 'うまく逃げ出した！',
  fleeFail: 'しかし回り込まれてしまった！',
  cannotFlee: 'この戦いから逃げることはできない！',
  enemyDown: (name) => `${name}を たおした！`,
  actorDown: (name) => `${name}は 力尽きた…`,
  poisoned: (name) => `${name}は 毒におかされた！`,
  poisonDmg: (name, d) => `${name}は 毒で ${d}のダメージ！`,
  slept: (name) => `${name}は 眠ってしまった！`,
  sleeping: (name) => `${name}は 眠っている…`,
  wokeUp: (name) => `${name}は 目を覚ました！`,
  paralyzed: (name) => `${name}は 体がしびれた！`,
  paralyzedSkip: (name) => `${name}は 体がしびれて動けない！`,
  paraRecover: (name) => `${name}の しびれがとれた。`,
  cured: (name, st) => `${name}の ${st}が治った！`,
  alreadyStatus: 'しかし効かなかった！',
  statusMissed: 'しかし効かなかった！',
  buffUp: (name, stat) => `${name}の ${stat}が上がった！`,
  buffDown: (name, stat) => `${name}の ${stat}が下がった！`,
  buffMax: 'それ以上変わらなかった。',
  revived: (name) => `${name}は 生き返った！`,
  victory: '戦いに勝利した！',
  gotExpGold: (exp, gold) => `経験値${exp} と ${gold}Gを手に入れた！`,
  gotDrop: (item) => `${item}を手に入れた！`,
  levelUp: (name, lv) => `${name}は レベル${lv}に上がった！`,
  learnedSkill: (name, skill) => `${name}は ${skill}を おぼえた！`,
  partyWiped: '全滅してしまった…',
  targetSelect: 'ターゲットを選択',
  enemyRowBack: '後列',

  // フィールド
  chestGet: (item) => `宝箱をあけた！ ${item}を手に入れた！`,
  chestGold: (g) => `宝箱をあけた！ ${g}Gを手に入れた！`,
  chestEmpty: '宝箱は空っぽだ。',
  doorLocked: 'カギがかかっている。',
  doorUnlock: (key) => `${key}で とびらを開けた！`,
  nothingHere: 'なにもない。',
  rockPushed: 'ゴゴゴ…岩を押した。',
  rockBlocked: '岩は動かないようだ。',
  switchOn: 'カチッ。スイッチが入った！',
  cannotEnterYet: '今は入れないようだ。',

  // 宿屋・店・教会・酒場
  innPrompt: (price) => `一泊${price}Gです。お泊まりになりますか？`,
  innStay: '泊まる',
  innNo: 'やめる',
  innDone: 'おはようございます。皆さまの疲れはすっかり取れました！',
  innNoMoney: 'お金が足りないようですね…またのお越しを。',
  shopBuy: '買う',
  shopSell: '売る',
  shopLeave: 'やめる',
  shopWelcome: 'いらっしゃい！何をお求めかな？',
  shopBuyWho: 'だれが受け取る？（そうび品はあとでメニューから装備できます）',
  shopSoldOut: '在庫切れ',
  shopNoMoney: 'お金が足りないよ。',
  shopBought: (item) => `${item}を買った！`,
  shopSold: (item, g) => `${item}を ${g}Gで売った。`,
  shopNothingToSell: '売れる物を持っていないようだね。',
  shopCannotSellKey: '大事な物は売れないよ。',
  tavernTitle: '冒険者の酒場',
  tavernCreate: '仲間をつくる',
  tavernAdd: 'パーティに入れる',
  tavernRemove: 'パーティから外す',
  tavernLeave: 'やめる',
  tavernFull: 'パーティは4人までです。',
  tavernRosterFull: 'これ以上仲間を登録できません。（最大8人）',
  tavernLastOne: '最後のひとりは外せません。',
  tavernHeroStay: '主人公は外せません。',
  tavernCreated: (name) => `${name}が仲間に加わった！`,
  tavernBench: 'ひかえ',
  formationHint: '入れ替える2人を順に選んでください。',
  formationDone: '隊列を入れ替えた。',

  // ゲームオーバー
  gameOverMsg: 'しかし、光はまだ消えていない…',
  gameOverRevive: '教会で目を覚ました。所持金が半分になった…',

  // オーブ
  orbGet: (orb) => `${orb}を手に入れた！ 世界に光がひとつ戻った…`,
  orbCount: (n) => `オーブ：${n} / 6`,

  // エンディング
  endingTitle: 'エルデアに光は戻った',
  postGameMsg: '…しかし、世界の裏側で 新たな闇がうごめき始めた。ハーベルの町の北の祠に、黄昏への道が開かれたという…',
  trueEndTitle: '― 真の平和 ―',
  theEnd: 'THE END',
  thanks: 'あそんでくれて ありがとう！',
};
